name: 🏗️ Template for Update CRDs on Go project
on:
  workflow_call:
    inputs:
      TARGET_REPO:
        required: true
        type: string
      TARGET_BRANCH:
        required: true
        type: string
      CRDS_VERSION:
        required: true
        type: string
jobs:
  update-crds:
    runs-on: ubuntu-latest
    steps:
      - name: checkout target repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.TARGET_REPO }}
          ref: ${{ inputs.TARGET_BRANCH }}
          token: ${{ secrets.GH_TOKEN }}
      - name: set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: setup proxy credentials
        run: |
          cat <<EOF > ~/.netrc
          ${{secrets.GOPROXY_CREDS}}
          EOF
      - name: update go.mod
        env:
          GONOSUMDB: github.com/traefik/hub-crds
          GOPROXY: https://proxy.golang.org,https://athens.traefiklabs.tech,direct
        run: |
          sed -i -e "s|github.com/traefik/hub-crds .*|github.com/traefik/hub-crds ${{ inputs.CRDS_VERSION }}|g" go.mod
          go mod tidy
      - name: create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "chore: update CRDs to ${{ inputs.CRDS_VERSION }}"
          committer: "Traefiker <traefiker@github.com>"
          author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          signoff: false
          branch: update-crds-${{ inputs.CRDS_VERSION }}
          delete-branch: true
          title: 'chore: update CRDs to ${{ inputs.CRDS_VERSION }}'
          labels: kind/enhancement,status/2-needs-review
          body: |
            This PR was automatically created by ${{ github.workflow }} workflow on run [#${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).

            This was triggered by commit [${{ github.ref }}](https://github.com/${{ github.repository }}/commits/${{ github.sha }}) on [${{ github.repository }}](https://github.com/${{ github.repository }}).
